### ISSUE TITLE
openOrSwitch doesn't work when no pane is opened

### ISSUE THREAD

**Issue by Vinzent03** [obsidian-community/obsidian-community-lib#17]
[openOrSwitch](https://github.com/obsidian-community/obsidian-community-lib/blob/main/src/utils.ts#L229) tries to access the path of the active file, which is undefined when there is no active file.

**Comment by SkepticMystic** [comment]
Ahh good point! I think we don't need to change much, because getFirstLinkpathDest doesn't _have to_ have a second argument. So we can just leave that blank, and therefore don't need to current file to run.
I'll change that some time today

**Comment by SkepticMystic** [comment]
@Vinzent03 should be fixed one the PR is merged 👍🏼
